import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Lexend, Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
});
const lexend = Lexend({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
